#!/usr/bin/env python3
"""Assemble the English dictionary from translated batches.

Reads backend/data/dictionary.json (KO) + backend/data/en-batches/batch_NNN.en.json
(translated rows) + meta.en.json (field names), then writes:
  - backend/data/dictionary.en.json
  - frontend/data.en.js  (window.WORD_DATA_EN = {...})

Structure/ids are preserved; only display text is replaced. Missing
translations fall back to the Korean text so the app never shows blanks.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT.parent / "frontend"
SRC = ROOT / "data" / "dictionary.json"
BATCHES = ROOT / "data" / "en-batches"

KIND = {"전문 용어": "Technical term", "현장 표현": "Field expression"}
EVIDENCE = {
    "공개 자료 확인": "Verified from public sources",
    "복수 자료 대조": "Cross-checked across sources",
    "일반 지식 기반 · 외부 출처 미첨부": "Based on general knowledge · no external source attached",
}

data = json.loads(SRC.read_text(encoding="utf-8"))

# collect translations by id
tr = {}
for f in sorted(BATCHES.glob("batch_*.en.json")):
    for row in json.loads(f.read_text(encoding="utf-8")):
        tr[row["id"]] = row

meta_path = BATCHES / "meta.en.json"
field_names = {}
if meta_path.exists():
    field_names = json.loads(meta_path.read_text(encoding="utf-8")).get("fields", {})

# field names
for fld in data["fields"]:
    fld["name"] = field_names.get(fld["id"], fld["name"])

missing = 0
for e in data["entries"]:
    t = tr.get(e["id"])
    if not t:
        missing += 1
        # still translate kind/evidence for consistency
        e["kind"] = KIND.get(e.get("kind"), e.get("kind"))
        e["evidence"] = EVIDENCE.get(e.get("evidence"), e.get("evidence"))
        continue
    for k in ("term", "definition", "example", "note", "category"):
        if t.get(k):
            e[k] = t[k]
    if t.get("aliases"):
        e["aliases"] = t["aliases"]
    e["kind"] = KIND.get(e.get("kind"), e.get("kind"))
    e["evidence"] = EVIDENCE.get(e.get("evidence"), e.get("evidence"))

data["lang"] = "en"

(ROOT / "data" / "dictionary.en.json").write_text(
    json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
)
(FRONTEND / "data.en.js").write_text(
    "/* Generated by scripts/assemble_en.py. English dictionary. */\n"
    "window.WORD_DATA_EN = "
    + json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")
    + ";\n",
    encoding="utf-8",
)
print(json.dumps({"entries": len(data["entries"]), "translated": len(tr), "missing": missing}))
