"""Detect unreviewed content changes; hashes do not establish semantic correctness.
The ledger is intentionally not regenerated by build_data.py.
"""
from pathlib import Path
import hashlib,json
ROOT=Path(__file__).resolve().parents[1]
CONTENT_KEYS=['id','field','term','english','definition','example','note','category','aliases','phrases','sources']
def signature(entry):
 raw=json.dumps([entry.get(k) for k in CONTENT_KEYS],ensure_ascii=False,separators=(',',':'))
 return hashlib.sha256(raw.encode()).hexdigest()
def check(entries):
 ledger=json.loads((ROOT/'data'/'reviewed-meanings.json').read_text())
 actual={e['id']:signature(e) for e in entries}
 reviewed={e['id']:e['signature'] for e in ledger['entries']}
 changed=[key for key,value in actual.items() if reviewed.get(key)!=value]
 removed=sorted(set(reviewed)-set(actual))
 assert not changed and not removed, '뜻·분야·예문 재검토 필요: '+str({'changed':changed,'removed':removed})
 return len(actual)
if __name__=='__main__':
 print(f"검토 기록과 {check(json.loads((ROOT/'data'/'dictionary.json').read_text())['entries'])}개 항목 일치")
